In [1]:
import numpy as np


In [2]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.size

3

In [8]:
a.itemsize

8

In [9]:
a.data

In [15]:
b= np.array([
    [1,2,3],
    [4,5,6]
])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print('Type: ', b.dtype)
print('Number of dimentions: ', b.ndim)
print('Shape: ', b.shape)
print('size: ', b.size)

Type:  int64
Number of dimentions:  2
Shape:  (2, 3)
size:  6


In [17]:
c=np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
print('Type: ', c.dtype)
print('Number of dimentions: ', c.ndim)
print('Shape: ', c.shape)
print('size: ', c.size)

Type:  int64
Number of dimentions:  3
Shape:  (2, 2, 2)
size:  8


In [24]:
d= np.array(["Apple", "Orange"])
d.dtype

dtype('<U6')

In [23]:
d= np.array([True,False])
d.dtype

dtype('bool')

In [22]:
d= np.array(['x',0,True])
d.dtype

dtype('<U21')

In [25]:
d= np.array(['1','2'])
d.astype(int)

array([1, 2])

In [26]:
d= np.array([(1,2),(3,4),[5,6]])
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [31]:
np.arange(3,12,3)

array([3, 6, 9])

In [33]:
np.linspace(3,12,3)

array([ 3. ,  7.5, 12. ])

In [34]:
np.random.random((2,2))

array([[0.97179055, 0.12892082],
       [0.6418967 , 0.61252988]])

In [35]:
np.random.rand(3,2)

array([[0.58846197, 0.98971431],
       [0.21841742, 0.36411288],
       [0.64148359, 0.77149846]])

In [36]:
np.random.randn(2,1)

array([[-0.78936212],
       [ 0.39616664]])

In [37]:
np.random.randint(3,15)

3

In [38]:
np.random.randint(3, size=8)

array([1, 0, 2, 2, 0, 2, 2, 0])

In [39]:
np.random.randint(3, size=(2,2))

array([[2, 0],
       [1, 0]])

In [44]:
np.full( (4,4), [1,2,3,4] )


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [46]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [59]:
a=np.arange (0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
a.shape=(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a.ravel() #changing the of matrix important for building modules in ML

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [65]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [66]:
b= np.arange(4,8)
b

array([4, 5, 6, 7])

In [68]:
a+b

array([ 4,  6,  8, 10])

In [69]:
np.add(a,b)

array([ 4,  6,  8, 10])

In [70]:
a*b 

array([ 0,  5, 12, 21])

In [71]:
np.multiply(a,b)

array([ 0,  5, 12, 21])

In [73]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [75]:
np.divide (a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [90]:
a = np.array([[4,5,6], [8,9,7]])
a.shape

(2, 3)

In [91]:
b = np.array([1,2,3])
b.shape

(3,)

In [89]:
c = np.dot (a,b)
c.shape

(3, 3)

In [82]:
a= np.arange(4,13).reshape(3,3)
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
a.dot(b)

array([[15., 15., 15.],
       [24., 24., 24.],
       [33., 33., 33.]])

In [87]:
b.dot(a)

array([[21., 24., 27.],
       [21., 24., 27.],
       [21., 24., 27.]])

In [104]:
a= np.arange(1,5)
a

array([1, 2, 3, 4])

In [105]:
a += 10
a

array([11, 12, 13, 14])

In [106]:
np.sqrt(a)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [107]:
np.log(a)

array([2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [108]:
np.sin(a)

array([-0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [109]:
x= np.array([11, 12, 13, 14])
x

array([11, 12, 13, 14])

In [110]:
x.std()

np.float64(1.118033988749895)

In [111]:
x=np. arange(10, 18). reshape( (2,4))
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [128]:
for row in x:
    for item in row:
        print (item)

10
11
12
13
14
15
16
17


In [127]:
for item in a.flat:
    print (item)

11
12
13
14


In [123]:
x=np.arange(10, 18).reshape( (2,4))
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [124]:
def func1(x):
    return x + 200


In [125]:
np.apply_along_axis(func1, axis=0, arr=a)

array([211, 212, 213, 214])

In [129]:
a= np.random.random((4,4))
a

array([[0.40526159, 0.32237198, 0.02982347, 0.2506544 ],
       [0.53766733, 0.51347642, 0.52038674, 0.31617905],
       [0.90155278, 0.1045888 , 0.30531871, 0.90876226],
       [0.27439919, 0.95337038, 0.38907001, 0.55385492]])

In [130]:
a[a<0.2] # as in consitions 

array([0.02982347, 0.1045888 ])

In [132]:
x= np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [133]:
y= np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
np.vstack((x,y)) #same as row_stack

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
np.hstack((x,y))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [136]:
x = np.array([1,2,3])
y = np.array([5,6,7])
z = np.array([8,9,2])


In [141]:
np.column_stack((x,y,z))

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 2]])

In [143]:
a= np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
[b,c]=np.hsplit(a,2)

In [145]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [146]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])